/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.platzhaltr.util.date.node;

import com.platzhaltr.util.date.analysis.*;

@SuppressWarnings("nls")
public final class ANextEntry extends PEntry
{
    private PRelative _relative_;
    private PTime _time_;

    public ANextEntry()
    {
        // Constructor
    }

    public ANextEntry(
        @SuppressWarnings("hiding") PRelative _relative_,
        @SuppressWarnings("hiding") PTime _time_)
    {
        // Constructor
        setRelative(_relative_);

        setTime(_time_);

    }

    @Override
    public Object clone()
    {
        return new ANextEntry(
            cloneNode(this._relative_),
            cloneNode(this._time_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextEntry(this);
    }

    public PRelative getRelative()
    {
        return this._relative_;
    }

    public void setRelative(PRelative node)
    {
        if(this._relative_ != null)
        {
            this._relative_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relative_ = node;
    }

    public PTime getTime()
    {
        return this._time_;
    }

    public void setTime(PTime node)
    {
        if(this._time_ != null)
        {
            this._time_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._time_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relative_)
            + toString(this._time_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relative_ == child)
        {
            this._relative_ = null;
            return;
        }

        if(this._time_ == child)
        {
            this._time_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relative_ == oldChild)
        {
            setRelative((PRelative) newChild);
            return;
        }

        if(this._time_ == oldChild)
        {
            setTime((PTime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
