/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.platzhaltr.util.date.node;

import com.platzhaltr.util.date.analysis.*;

@SuppressWarnings("nls")
public final class AYearRelative extends PRelative
{
    private TYear _year_;

    public AYearRelative()
    {
        // Constructor
    }

    public AYearRelative(
        @SuppressWarnings("hiding") TYear _year_)
    {
        // Constructor
        setYear(_year_);

    }

    @Override
    public Object clone()
    {
        return new AYearRelative(
            cloneNode(this._year_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAYearRelative(this);
    }

    public TYear getYear()
    {
        return this._year_;
    }

    public void setYear(TYear node)
    {
        if(this._year_ != null)
        {
            this._year_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._year_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._year_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._year_ == child)
        {
            this._year_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._year_ == oldChild)
        {
            setYear((TYear) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
