/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.platzhaltr.util.date.lexer;

import java.io.*;
import com.platzhaltr.util.date.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNext(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMonday(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThuesday(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWednesday(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTuersday(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFriday(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSaturday(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSunday(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWeekend(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWeek(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMonth(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TYear(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEvery(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJanuary(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFebruary(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMarch(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TApril(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMay(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJune(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJuly(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAugust(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeptember(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOctober(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNovember(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDecember(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOn(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAt(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOclock(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWord(text, line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {46, 46, 4}, {48, 57, 5}, {58, 58, 6}, {65, 65, 7}, {66, 67, 8}, {68, 68, 9}, {69, 69, 8}, {70, 70, 10}, {71, 72, 8}, {73, 73, 11}, {74, 74, 12}, {75, 76, 8}, {77, 77, 13}, {78, 78, 14}, {79, 79, 15}, {80, 82, 8}, {83, 83, 16}, {84, 84, 8}, {85, 85, 17}, {86, 86, 8}, {87, 87, 18}, {88, 90, 8}, {97, 97, 19}, {98, 99, 8}, {100, 100, 20}, {101, 101, 8}, {102, 102, 21}, {103, 104, 8}, {105, 105, 22}, {106, 106, 23}, {107, 108, 8}, {109, 109, 24}, {110, 110, 25}, {111, 111, 26}, {112, 114, 8}, {115, 115, 27}, {116, 116, 8}, {117, 117, 28}, {118, 118, 8}, {119, 119, 29}, {120, 122, 8}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {},
            {{48, 57, 5}, },
            {},
            {{65, 90, 8}, {97, 108, 8}, {109, 109, 30}, {110, 111, 8}, {112, 112, 31}, {113, 116, 8}, {117, 117, 32}, {118, 122, 8}, },
            {{65, 90, 8}, {97, 122, 8}, },
            {{65, 90, 8}, {97, 100, 8}, {101, 101, 33}, {102, 104, 8}, {105, 105, 34}, {106, 110, 8}, {111, 111, 35}, {112, 122, 8}, },
            {{65, 100, -11}, {101, 101, 36}, {102, 113, 8}, {114, 114, 37}, {115, 122, 8}, },
            {{65, 90, 8}, {97, 109, 8}, {110, 110, 38}, {111, 122, 8}, },
            {{65, 90, 8}, {97, 97, 39}, {98, 100, 8}, {101, 101, 40}, {102, 116, 8}, {117, 117, 41}, {118, 122, 8}, },
            {{65, 90, 8}, {97, 97, 42}, {98, 104, 8}, {105, 105, 43}, {106, 110, 8}, {111, 111, 44}, {112, 122, 8}, {228, 228, 45}, },
            {{65, 90, 8}, {97, 110, 8}, {111, 111, 46}, {112, 122, 8}, {228, 228, 47}, },
            {{65, 90, 8}, {97, 106, 8}, {107, 107, 48}, {108, 122, 8}, },
            {{65, 90, 8}, {97, 97, 49}, {98, 100, 8}, {101, 101, 50}, {102, 110, 8}, {111, 111, 51}, {112, 122, 8}, },
            {{65, 90, 8}, {97, 103, 8}, {104, 104, 52}, {105, 122, 8}, },
            {{65, 68, 8}, {69, 69, 53}, {70, 90, 8}, {97, 100, 8}, {101, 101, 54}, {102, 110, 8}, {111, 111, 55}, {112, 122, 8}, },
            {{65, 108, -9}, {109, 109, 56}, {110, 111, 8}, {112, 112, 57}, {113, 116, 8}, {117, 117, 58}, {118, 122, 8}, },
            {{65, 100, -11}, {101, 101, 59}, {102, 104, 8}, {105, 105, 60}, {106, 110, 8}, {111, 111, 61}, {112, 122, 8}, },
            {{65, 100, -11}, {101, 101, 62}, {102, 113, 8}, {114, 114, 63}, {115, 122, 8}, },
            {{65, 109, -13}, {110, 110, 64}, {111, 122, 8}, },
            {{65, 90, 8}, {97, 97, 65}, {98, 100, 8}, {101, 101, 66}, {102, 116, 8}, {117, 117, 67}, {118, 122, 8}, },
            {{65, 90, 8}, {97, 97, 68}, {98, 104, 8}, {105, 105, 69}, {106, 110, 8}, {111, 111, 70}, {112, 122, 8}, {228, 228, 71}, },
            {{65, 110, -16}, {111, 111, 72}, {112, 122, 8}, {228, 228, 73}, },
            {{65, 106, -17}, {107, 107, 74}, {108, 122, 8}, },
            {{65, 90, 8}, {97, 97, 75}, {98, 100, 8}, {101, 101, 76}, {102, 110, 8}, {111, 111, 77}, {112, 122, 8}, },
            {{65, 103, -19}, {104, 104, 78}, {105, 108, 8}, {109, 109, 79}, {110, 122, 8}, },
            {{65, 100, -11}, {101, 101, 80}, {102, 110, 8}, {111, 111, 81}, {112, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 113, 8}, {114, 114, 82}, {115, 122, 8}, },
            {{65, 90, 8}, {97, 102, 8}, {103, 103, 83}, {104, 122, 8}, },
            {{65, 90, 8}, {97, 121, 8}, {122, 122, 84}, },
            {{65, 100, -11}, {101, 101, 85}, {102, 122, 8}, },
            {{65, 109, -13}, {110, 110, 86}, {111, 122, 8}, },
            {{65, 90, 8}, {97, 97, 8}, {98, 98, 87}, {99, 122, 8}, },
            {{65, 100, -11}, {101, 101, 88}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 103, -19}, {104, 104, 89}, {105, 109, 8}, {110, 110, 90}, {111, 122, 8}, },
            {{65, 90, 8}, {97, 99, 8}, {100, 100, 91}, {101, 122, 8}, },
            {{65, 90, 8}, {97, 107, 8}, {108, 108, 92}, {109, 109, 8}, {110, 110, 93}, {111, 122, 8}, },
            {{65, 90, 8}, {97, 104, 8}, {105, 105, 94}, {106, 122, 8}, },
            {{65, 90, 8}, {97, 115, 8}, {116, 116, 95}, {117, 122, 8}, },
            {{65, 109, -13}, {110, 110, 96}, {111, 122, 8}, },
            {{114, 114, 97}, },
            {{65, 90, 8}, {97, 117, 8}, {118, 118, 98}, {119, 122, 8}, },
            {{99, 99, 99}, },
            {{65, 115, -45}, {116, 116, 100}, {117, 122, 8}, },
            {{65, 108, -9}, {109, 109, 101}, {110, 122, 8}, },
            {{65, 90, 8}, {97, 111, 8}, {112, 112, 102}, {113, 122, 8}, },
            {{65, 109, -13}, {110, 110, 103}, {111, 122, 8}, },
            {{65, 113, -33}, {114, 114, 104}, {115, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 98, 8}, {99, 99, 105}, {100, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 113, -33}, {114, 114, 106}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 107}, {104, 122, 8}, },
            {{65, 121, -35}, {122, 122, 108}, },
            {{65, 100, -11}, {101, 101, 109}, {102, 122, 8}, },
            {{65, 109, -13}, {110, 110, 110}, {111, 122, 8}, },
            {{65, 97, -38}, {98, 98, 111}, {99, 122, 8}, },
            {{65, 100, -11}, {101, 101, 112}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 109, -13}, {110, 110, 113}, {111, 122, 8}, },
            {{65, 99, -42}, {100, 100, 114}, {101, 122, 8}, },
            {{65, 107, -43}, {108, 108, 115}, {109, 109, 8}, {110, 110, 116}, {111, 122, 8}, },
            {{65, 104, -44}, {105, 105, 117}, {106, 122, 8}, },
            {{65, 115, -45}, {116, 116, 118}, {117, 122, 8}, },
            {{65, 109, -13}, {110, 110, 119}, {111, 122, 8}, },
            {{114, 114, 120}, },
            {{65, 117, -48}, {118, 118, 121}, {119, 122, 8}, },
            {{99, 99, 122}, },
            {{65, 115, -45}, {116, 116, 123}, {117, 122, 8}, },
            {{65, 108, -9}, {109, 109, 124}, {110, 122, 8}, },
            {{65, 111, -52}, {112, 112, 125}, {113, 122, 8}, },
            {{65, 109, -13}, {110, 110, 126}, {111, 122, 8}, },
            {{65, 113, -33}, {114, 114, 127}, {115, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 98, -57}, {99, 99, 128}, {100, 122, 8}, },
            {{65, 104, -44}, {105, 105, 129}, {106, 122, 8}, },
            {{65, 90, 8}, {97, 116, 8}, {117, 117, 130}, {118, 122, 8}, },
            {{65, 100, -11}, {101, 101, 131}, {102, 122, 8}, },
            {{65, 109, -13}, {110, 110, 132}, {111, 122, 8}, },
            {{65, 109, -13}, {110, 110, 133}, {111, 122, 8}, },
            {{65, 113, -33}, {114, 114, 134}, {115, 122, 8}, },
            {{65, 104, -44}, {105, 105, 135}, {106, 122, 8}, },
            {{65, 113, -33}, {114, 114, 136}, {115, 122, 8}, },
            {{65, 116, -85}, {117, 117, 137}, {118, 122, 8}, },
            {{65, 100, -11}, {101, 101, 138}, {102, 122, 8}, },
            {{65, 104, -44}, {105, 105, 139}, {106, 122, 8}, },
            {{65, 104, -44}, {105, 105, 140}, {106, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 115, -45}, {116, 116, 141}, {117, 122, 8}, },
            {{65, 90, 8}, {97, 97, 142}, {98, 115, 8}, {116, 116, 143}, {117, 122, 8}, },
            {{122, 122, 144}, },
            {{65, 100, -11}, {101, 101, 145}, {102, 122, 8}, },
            {{104, 104, 146}, },
            {{65, 110, -16}, {111, 111, 147}, {112, 122, 8}, },
            {{65, 90, 8}, {97, 114, 8}, {115, 115, 148}, {116, 122, 8}, },
            {{65, 115, -45}, {116, 116, 149}, {117, 122, 8}, },
            {{65, 109, -13}, {110, 110, 150}, {111, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 103, -19}, {104, 104, 151}, {105, 122, 8}, },
            {{65, 104, -44}, {105, 105, 152}, {106, 122, 8}, },
            {{65, 116, -85}, {117, 117, 153}, {118, 122, 8}, },
            {{65, 100, -11}, {101, 101, 154}, {102, 122, 8}, },
            {{65, 109, -13}, {110, 110, 155}, {111, 122, 8}, },
            {{65, 109, -13}, {110, 110, 156}, {111, 122, 8}, },
            {{65, 113, -33}, {114, 114, 157}, {115, 122, 8}, },
            {{65, 104, -44}, {105, 105, 158}, {106, 122, 8}, },
            {{65, 116, -85}, {117, 117, 159}, {118, 122, 8}, },
            {{65, 100, -11}, {101, 101, 160}, {102, 122, 8}, },
            {{65, 104, -44}, {105, 105, 161}, {106, 122, 8}, },
            {{65, 104, -44}, {105, 105, 162}, {106, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 115, -45}, {116, 116, 163}, {117, 122, 8}, },
            {{65, 115, -45}, {116, 116, 164}, {117, 122, 8}, },
            {{122, 122, 165}, },
            {{65, 100, -11}, {101, 101, 166}, {102, 122, 8}, },
            {{104, 104, 167}, },
            {{65, 110, -16}, {111, 111, 168}, {112, 122, 8}, },
            {{65, 114, -103}, {115, 115, 169}, {116, 122, 8}, },
            {{65, 115, -45}, {116, 116, 170}, {117, 122, 8}, },
            {{65, 109, -13}, {110, 110, 171}, {111, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 103, -19}, {104, 104, 172}, {105, 122, 8}, },
            {{65, 107, -43}, {108, 108, 173}, {109, 122, 8}, },
            {{65, 114, -103}, {115, 115, 174}, {116, 122, 8}, },
            {{65, 108, -9}, {109, 109, 175}, {110, 122, 8}, },
            {{65, 114, -103}, {115, 115, 176}, {116, 122, 8}, },
            {{65, 100, -11}, {101, 101, 177}, {102, 122, 8}, },
            {{65, 116, -85}, {117, 117, 178}, {118, 122, 8}, },
            {{65, 115, -45}, {116, 116, 179}, {117, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 97, 180}, {98, 122, 8}, },
            {{65, 109, -13}, {110, 110, 181}, {111, 113, 8}, {114, 114, 182}, {115, 115, 183}, {116, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 118, 8}, {119, 119, 184}, {120, 122, 8}, },
            {{65, 115, -45}, {116, 116, 185}, {117, 122, 8}, },
            {{65, 90, 8}, {97, 97, 186}, {98, 122, 8}, },
            {},
            {{65, 108, -9}, {109, 109, 187}, {110, 122, 8}, },
            {{115, 115, 188}, },
            {{65, 97, -38}, {98, 98, 189}, {99, 122, 8}, },
            {{65, 115, -45}, {116, 116, 190}, {117, 122, 8}, },
            {{65, 100, -11}, {101, 101, 191}, {102, 122, 8}, },
            {{65, 115, -45}, {116, 116, 192}, {117, 122, 8}, },
            {{65, 100, -11}, {101, 101, 193}, {102, 122, 8}, },
            {{65, 107, -43}, {108, 108, 194}, {109, 122, 8}, },
            {{65, 114, -103}, {115, 115, 195}, {116, 122, 8}, },
            {{65, 108, -9}, {109, 109, 196}, {110, 122, 8}, },
            {{65, 114, -103}, {115, 115, 197}, {116, 122, 8}, },
            {{65, 100, -11}, {101, 101, 198}, {102, 122, 8}, },
            {{65, 116, -85}, {117, 117, 199}, {118, 122, 8}, },
            {{65, 115, -45}, {116, 116, 200}, {117, 122, 8}, },
            {{65, 90, 8}, {97, 97, 201}, {98, 122, 8}, },
            {{65, 109, -13}, {110, 110, 202}, {111, 113, 8}, {114, 114, 203}, {115, 115, 204}, {116, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 118, -143}, {119, 119, 205}, {120, 122, 8}, },
            {{65, 90, 8}, {97, 97, 206}, {98, 122, 8}, },
            {},
            {{65, 108, -9}, {109, 109, 207}, {110, 122, 8}, },
            {{115, 115, 208}, },
            {{65, 97, -38}, {98, 98, 209}, {99, 122, 8}, },
            {{65, 115, -45}, {116, 116, 210}, {117, 122, 8}, },
            {{65, 100, -11}, {101, 101, 211}, {102, 122, 8}, },
            {{65, 115, -45}, {116, 116, 212}, {117, 122, 8}, },
            {{65, 100, -11}, {101, 101, 213}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 115, -45}, {116, 116, 214}, {117, 122, 8}, },
            {{65, 97, -38}, {98, 98, 215}, {99, 122, 8}, },
            {{65, 115, -45}, {116, 116, 216}, {117, 122, 8}, },
            {{65, 113, -33}, {114, 114, 217}, {115, 122, 8}, },
            {{65, 90, 8}, {97, 97, 218}, {98, 122, 8}, },
            {{65, 90, 8}, {97, 97, 219}, {98, 122, 8}, },
            {{65, 113, -33}, {114, 114, 220}, {115, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 110, -16}, {111, 111, 221}, {112, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 102, -34}, {103, 103, 222}, {104, 122, 8}, },
            {{65, 97, -38}, {98, 98, 223}, {99, 122, 8}, },
            {{116, 116, 224}, },
            {{65, 100, -11}, {101, 101, 225}, {102, 122, 8}, },
            {{65, 90, 8}, {97, 97, 226}, {98, 122, 8}, },
            {{65, 108, -9}, {109, 109, 227}, {110, 122, 8}, },
            {{65, 90, 8}, {97, 97, 228}, {98, 122, 8}, },
            {{65, 109, -13}, {110, 110, 229}, {111, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 115, -45}, {116, 116, 230}, {117, 122, 8}, },
            {{65, 97, -38}, {98, 98, 231}, {99, 122, 8}, },
            {{65, 115, -45}, {116, 116, 232}, {117, 122, 8}, },
            {{65, 113, -33}, {114, 114, 233}, {115, 122, 8}, },
            {{65, 90, 8}, {97, 97, 234}, {98, 122, 8}, },
            {{65, 90, 8}, {97, 97, 235}, {98, 122, 8}, },
            {{65, 113, -33}, {114, 114, 236}, {115, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 110, -16}, {111, 111, 237}, {112, 122, 8}, },
            {{65, 102, -34}, {103, 103, 238}, {104, 122, 8}, },
            {{65, 97, -38}, {98, 98, 239}, {99, 122, 8}, },
            {{116, 116, 240}, },
            {{65, 100, -11}, {101, 101, 241}, {102, 122, 8}, },
            {{65, 90, 8}, {97, 97, 242}, {98, 122, 8}, },
            {{65, 108, -9}, {109, 109, 243}, {110, 122, 8}, },
            {{65, 90, 8}, {97, 97, 244}, {98, 122, 8}, },
            {{65, 109, -13}, {110, 110, 245}, {111, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 246}, {102, 122, 8}, },
            {{65, 90, 8}, {97, 97, 247}, {98, 122, 8}, },
            {{65, 114, -103}, {115, 115, 248}, {116, 122, 8}, },
            {{65, 113, -33}, {114, 114, 249}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 250}, {104, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 98, -57}, {99, 99, 251}, {100, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 252}, {102, 122, 8}, },
            {{101, 101, 253}, },
            {{65, 113, -33}, {114, 114, 254}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 255}, {104, 122, 8}, },
            {{65, 97, -38}, {98, 98, 256}, {99, 122, 8}, },
            {{65, 102, -34}, {103, 103, 257}, {104, 122, 8}, },
            {{65, 100, -11}, {101, 101, 258}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 259}, {102, 122, 8}, },
            {{65, 90, 8}, {97, 97, 260}, {98, 122, 8}, },
            {{65, 114, -103}, {115, 115, 261}, {116, 122, 8}, },
            {{65, 113, -33}, {114, 114, 262}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 263}, {104, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 98, -57}, {99, 99, 264}, {100, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 265}, {102, 122, 8}, },
            {{101, 101, 266}, },
            {{65, 113, -33}, {114, 114, 267}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 268}, {104, 122, 8}, },
            {{65, 97, -38}, {98, 98, 269}, {99, 122, 8}, },
            {{65, 102, -34}, {103, 103, 270}, {104, 122, 8}, },
            {{65, 100, -11}, {101, 101, 271}, {102, 122, 8}, },
            {{65, 113, -33}, {114, 114, 272}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 273}, {104, 122, 8}, },
            {{65, 115, -45}, {116, 116, 274}, {117, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 103, -19}, {104, 104, 275}, {105, 122, 8}, },
            {{65, 113, -33}, {114, 114, 276}, {115, 122, 8}, },
            {{110, 110, 277}, {115, 115, 278}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 279}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 109, -13}, {110, 110, 280}, {111, 122, 8}, },
            {{65, 113, -33}, {114, 114, 281}, {115, 122, 8}, },
            {{65, 102, -34}, {103, 103, 282}, {104, 122, 8}, },
            {{65, 115, -45}, {116, 116, 283}, {117, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 103, -19}, {104, 104, 284}, {105, 122, 8}, },
            {{65, 113, -33}, {114, 114, 285}, {115, 122, 8}, },
            {{110, 110, 286}, {115, 115, 287}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 288}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 109, -13}, {110, 110, 289}, {111, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 97, 290}, {98, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {},
            {},
            {{65, 113, -33}, {114, 114, 291}, {115, 122, 8}, },
            {{65, 99, -42}, {100, 100, 292}, {101, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 90, 8}, {97, 97, 293}, {98, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {},
            {},
            {{65, 113, -33}, {114, 114, 294}, {115, 122, 8}, },
            {{65, 99, -42}, {100, 100, 295}, {101, 122, 8}, },
            {{65, 102, -34}, {103, 103, 296}, {104, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 297}, {102, 122, 8}, },
            {{65, 102, -34}, {103, 103, 298}, {104, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 100, -11}, {101, 101, 299}, {102, 122, 8}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
            {{65, 122, -10}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 31, 31, 31, 25, 33, 26, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 27, 32, 32, 32, 32, 32, 32, 32, 28, 32, 32, 32, 32, 32, 32, -1, 32, -1, 32, 32, 32, 32, 32, 8, 8, 32, 27, 32, 32, 32, 2, 4, 32, 5, 28, 32, 32, 32, 32, 3, 1, -1, 32, -1, 32, 6, 32, 7, 32, 29, 8, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 17, 32, 32, -1, 32, -1, 32, 32, 32, 32, 30, 32, 32, 20, 24, 32, 32, 14, 32, 13, 32, 32, 32, 17, 32, 32, -1, 23, -1, 22, 32, 21, 32, 30, 32, 32, 32, 32, 32, 32, 32, 32, 11, 32, 32, 19, 18, 32, 32, 32, 15, 32, -1, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 19, 18, 32, 32, 15, 32, -1, 32, 32, 32, 32, 32, 16, 32, 32, 32, 32, 32, 32, 32, 12, 12, 12, 32, 10, 32, 32, -1, 32, 32, 32, 32, 9, 16, 32, 32, 32, 32, 32, 32, 32, 12, 12, 12, 32, 32, 32, -1, 32, 32, 32, 32, 9, 20, 32, 32, 32, 32, 32, 13, 32, 1, 32, -1, 32, 32, 32, 32, 32, 20, 32, 32, 32, 32, 32, 13, 32, 1, 32, -1, 32, 32, 32, 32, 32, 32, 32, 32, 14, 5, 32, 32, 0, 22, 6, 32, 7, 32, 32, 32, 32, 14, 5, 32, 32, 0, 22, 6, 32, 7, 32, 24, 2, 32, 3, 23, 0, 0, 32, 32, 24, 2, 32, 3, 23, 0, 0, 32, 32, 32, 21, 32, 32, 21, 32, 4, 8, 4, 8, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
